### ISSUE TITLE
Run generate after deleting schema, but before deleting files

### ISSUE THREAD

**Issue by ivanvanderbyl** [a8m/entclean#1]
Thanks for this incredible useful tool @a8m — a little issue I've run into is when using Privacy we end up with a dependency graph from schema -> privacy -> ./ent, which means that deleting the source files for a node before generating breaks a bunch of references, and stops ent from generating new code. A simple fix for this seems to be to change the order of operations to:

1. Delete `ent/schema/<node>.go`
2. Run generate
3. Delete `ent/<node>_create.go` etc
4. Optionally, run generate again, although might not be necessary.

**Comment by a8m** [comment]
Hey, @ivanvanderbyl 👋🏻

I have merged this logic into ent a ~year ago. Can you open issue there? I’m not able to transfer it to a different account.

Thanks for reporting this.

**Comment by ivanvanderbyl** [comment]
Oh I hadn't noticed, no worries, I'll open there if it's still an issue in ent actual.
